name: Turisten
safe: true
lsi: false
pygments: true
baseurl: /turisten
exclude: [config.rb, sass]
permalink: /blog/:year/:month/:title
timezone: Europe/Stockholm
paginate: 10
paginate_path: /blog/page:num