name: Turisten
safe: true
lsi: false
pygments: true
baseurl: /turisten
exclude: [config.rb, sass]
permalink: /:year/:month/:title
timezone: Europe/Stockholm
paginate: 10

# Prose settings
prose:
  rooturl: "_posts"
  media: "media"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: " "
      - name: "country"
        field:
          element: "multiselect"
          label: "Country"
          placeholder: "Choose country"
          options:
            - name: "southkorea"
              value: "Sydkorea"
            - name: "germany"
              value: "Tyskland"
            - name: "denmark"
              value: "Danmark"
            - name: "australia"
              value: "Australien"
            - name: "sweden"
              value: "Sverige"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          placeholder: "Select author"
          options:
            - name: "gustaf"
              value: "Gustaf"
            - name: "linn"
              value: "Linn"