name: Turisten
safe: true
lsi: false
pygments: true
baseurl: /turisten
exclude: [config.rb, sass]
permalink: /:year/:month/:title
timezone: Europe/Stockholm
paginate: 10

# Prose settings
prose:
  rooturl: "_posts"
  media: "media"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "country"
        field:
          element: "multiselect"
          label: "Country"
          placeholder: "Choose country"
          options:
            - name: "Australien"
              value: "Australien"
            - name: "Denmark"
              value: "Danmark"
            - name: "Indonesien"
              value: "Indonesien"
            - name: "Filippinerna"
              value: "Filippinerna"
            - name: "Singapore"
              value: "Singapore"
            - name: "Sverige"
              value: "Sverige"
            - name: "Sydkorea"
              value: "Sydkorea"
            - name: "Tyskland"
              value: "Tyskland"
      - name: "image"
        field:
          element: "text"
          label: "Image"
          value: ""
      - name: "vimeo"
        field:
          element: "text"
          label: "Vimeo video ID"
          value: ""
      - name: "youtube"
        field:
          element: "text"
          label: "Youtube video ID"
          value: ""
      - name: "author"
        field:
          element: "select"
          label: "Author"
          placeholder: "Select author"
          options:
            - name: "Gustaf"
              value: "Gustaf"
            - name: "Linn"
              value: "Linn"