name: Turisten
safe: true
lsi: false
pygments: true
baseurl: /turisten
exclude: [config.rb, sass]
permalink: /:year/:month/:title
timezone: Europe/Stockholm
paginate: 10

# Authors
authors:
  gustaf:
    name: Gustaf
    avatar: avatar-gustaf.png
  linn:
    name: Linn
    avatar: avatar-linn.png