name: Turisten
safe: true
lsi: false
pygments: true
baseurl: /turisten
exclude: [node_modules, bower_components, assets/javascripts, assets/stylesheets]
permalink: /:year/:month/:title
timezone: Europe/Stockholm
paginate: 15

# Authors
authors:
  gustaf:
    name: Gustaf
    avatar: avatar-gustaf.png
  linn:
    name: Linn
    avatar: avatar-linn.png